export const queryKeys = {
  automation: ["automation"] as const,
  processes: ["automation", "processes"] as const,
  incidents: (filters: object = {}) => ["incidents", filters] as const,
  incident: (id: number) => ["incidents", id] as const,
  workflows: (filters: object = {}) => ["workflows", filters] as const,
  workflow: (id: number) => ["workflows", id] as const,
  batches: (filters: object = {}) => ["batches", filters] as const,
  batch: (id: number) => ["batches", id] as const,
  workItems: (filters: object = {}) => ["work-items", filters] as const,
  workItem: (id: number) => ["work-items", id] as const,
  videos: (filters: object = {}) => ["videos", filters] as const,
  video: (id: number) => ["videos", id] as const,
  transcripts: (filters: object = {}) => ["transcripts", filters] as const,
  transcript: (id: number) => ["transcripts", id] as const,
  publishing: ["publishing"] as const,
  channels: ["channels"] as const,
  streamers: ["streamers"] as const,
  knowledge: (filters: object = {}) => ["knowledge", filters] as const,
  prompts: ["prompts"] as const,
  events: (filters: object = {}) => ["events", filters] as const,
  usage: ["usage"] as const,
  schema: ["schema"] as const,
};
