"use client";

import type { ColumnDef } from "@tanstack/react-table";
import { type FormEvent, useState } from "react";

import { ActionDialog } from "@/components/action-dialog";
import { DataTable } from "@/components/data-table";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Panel } from "@/components/ui/panel";
import type { ChannelList, Streamer } from "@/features/catalog/api";
import { useChannels, useStreamers } from "@/features/catalog/api";
import { useCreateChannel, useCreateStreamer, useDeleteChannel, useDeleteStreamer, useUpdateChannel, useUpdateStreamer } from "@/features/configuration/api";
import { formatDateTime, formatNumber } from "@/lib/format";

type ChannelRow = ChannelList["items"][number];

export function ChannelsConsole({ initialChannels, initialStreamers }: { initialChannels: ChannelList | null; initialStreamers: Streamer[] | null }) {
  const channels = useChannels(initialChannels); const streamers = useStreamers(initialStreamers);
  const createStreamer = useCreateStreamer(); const updateStreamer = useUpdateStreamer(); const deleteStreamer = useDeleteStreamer(); const createChannel = useCreateChannel(); const updateChannel = useUpdateChannel(); const deleteChannel = useDeleteChannel();
  const [editing, setEditing] = useState<ChannelRow | null>(null);
  const columns: ColumnDef<ChannelRow>[] = [
    { header: "ID", accessorKey: "channelId", cell: ({ getValue }) => <code translate="no">#{String(getValue())}</code> },
    { header: "채널", accessorKey: "name", cell: ({ row }) => <div><p className="font-medium">{row.original.name}</p><code className="text-xs text-[var(--muted)]" translate="no">{row.original.handle}</code></div> },
    { header: "Streamer", accessorKey: "streamerName", cell: ({ row }) => <span>{row.original.streamerName} <code translate="no">#{row.original.streamerId}</code></span> },
    { header: "영상", accessorKey: "videoCount", cell: ({ getValue }) => <span className="ops-number">{formatNumber(Number(getValue()))}</span> },
    { header: "작업", accessorKey: "taskRunningCount", cell: ({ row }) => <span className="ops-number">running {row.original.taskRunningCount} · failed {row.original.taskFailedCount}</span> },
    { header: "최근 영상", accessorKey: "latestVideoPublishedAt", cell: ({ getValue }) => <span className="ops-number whitespace-nowrap">{formatDateTime(String(getValue() ?? ""))}</span> },
    { header: "조작", id: "actions", cell: ({ row }) => <div className="flex gap-2"><Button size="sm" onClick={() => setEditing(row.original)}>수정</Button><ActionDialog.Provider heading={`채널 #${row.original.channelId} 삭제`} description={`${row.original.name} 채널을 삭제합니다. ID와 사유를 확인하세요.`} confirmLabel="삭제" confirmationValue={String(row.original.channelId)} reasonRequired tone="danger" onConfirm={async (reason) => { await deleteChannel.mutateAsync({ id: row.original.channelId, reason }); }}><ActionDialog.Trigger><Button size="sm" variant="destructive">삭제</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ReasonField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider></div> },
  ];
  function submitStreamer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void createStreamer.mutateAsync({ name: String(form.get("name")) }).then(() => event.currentTarget.reset()); }
  function submitChannel(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void createChannel.mutateAsync({ streamerId: Number(form.get("streamerId")), body: { name: String(form.get("name")), handle: String(form.get("handle")), youtubeChannelId: String(form.get("youtubeChannelId")) || null } }).then(() => event.currentTarget.reset()); }
  function saveChannel(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); void updateChannel.mutateAsync({ id: editing.channelId, body: { name: String(form.get("name")), handle: String(form.get("handle")), youtubeChannelId: String(form.get("youtubeChannelId")) || null } }).then(() => setEditing(null)); }
  return <><PageHeader eyebrow="구성" heading="채널 & Streamer" description="수집 대상 소유 관계를 관리하고 채널별 파이프라인 처리량을 확인합니다." />
    <div className="mb-4 grid gap-4 xl:grid-cols-2"><Panel.Root><Panel.Header><Panel.Title>Streamer 관리</Panel.Title><Panel.Description>추가·이름 변경·삭제</Panel.Description></Panel.Header><Panel.Body><form onSubmit={submitStreamer} className="mb-4 flex gap-2"><input name="name" required minLength={1} className="min-h-10 min-w-0 flex-1 rounded-md border bg-[var(--surface)] px-3 text-sm" placeholder="새 streamer 이름" /><Button type="submit" variant="primary" disabled={createStreamer.isPending}>추가</Button></form><div className="grid gap-2">{streamers.data?.map((streamer) => <div key={streamer.id} className="flex flex-wrap items-center gap-2 rounded-md border p-2"><form className="flex min-w-0 flex-1 gap-2" onSubmit={(event) => { event.preventDefault(); const name = String(new FormData(event.currentTarget).get("name")); void updateStreamer.mutateAsync({ id: streamer.id, body: { name } }); }}><code className="self-center" translate="no">#{streamer.id}</code><input name="name" defaultValue={streamer.name} aria-label={`Streamer #${streamer.id} 이름`} className="min-h-10 min-w-0 flex-1 rounded-md border bg-[var(--surface)] px-3 text-sm" /><Button type="submit">저장</Button></form><ActionDialog.Provider heading={`Streamer #${streamer.id} 삭제`} description={`${streamer.name}과 연결 관계를 삭제합니다.`} confirmLabel="삭제" confirmationValue={String(streamer.id)} reasonRequired tone="danger" onConfirm={(reason) => deleteStreamer.mutateAsync({ id: streamer.id, reason }).then(() => undefined)}><ActionDialog.Trigger><Button variant="destructive">삭제</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ReasonField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider></div>)}</div></Panel.Body></Panel.Root>
      <Panel.Root><Panel.Header><Panel.Title>{editing ? `채널 #${editing.channelId} 수정` : "채널 추가"}</Panel.Title><Panel.Description>handle과 YouTube channel ID를 함께 관리</Panel.Description></Panel.Header><Panel.Body><form key={editing?.channelId ?? "new"} onSubmit={editing ? saveChannel : submitChannel} className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-medium">Streamer<select name="streamerId" disabled={Boolean(editing)} required defaultValue={editing?.streamerId} className="min-h-10 rounded-md border bg-[var(--surface)] px-3 text-sm">{streamers.data?.map((streamer) => <option key={streamer.id} value={streamer.id}>{streamer.name}</option>)}</select></label><Field name="name" label="이름" defaultValue={editing?.name} /><Field name="handle" label="Handle" defaultValue={editing?.handle} /><Field name="youtubeChannelId" label="YouTube channel ID" defaultValue={editing?.youtubeChannelId ?? ""} /><div className="flex gap-2 sm:col-span-2"><Button type="submit" variant="primary" disabled={createChannel.isPending || updateChannel.isPending}>{editing ? "변경 저장" : "채널 추가"}</Button>{editing && <Button type="button" onClick={() => setEditing(null)}>취소</Button>}</div></form></Panel.Body></Panel.Root></div>
    <DataTable.Provider rows={channels.data?.items ?? []} columns={columns} getRowId={(row) => String(row.channelId)} state={{ initialLoading: channels.isLoading, refreshing: channels.isFetching && !channels.isLoading, placeholder: channels.isPlaceholderData, error: channels.error?.message ?? null }} meta={{ label: "채널 목록", emptyTitle: "등록된 채널이 없습니다.", emptyDescription: "Streamer를 만들고 수집 채널을 추가하세요." }}><DataTable.Frame><DataTable.Toolbar><span className="text-sm text-[var(--muted)]">{formatNumber(channels.data?.items.length)}개 채널</span></DataTable.Toolbar><DataTable.Content /></DataTable.Frame></DataTable.Provider>
  </>;
}

function Field({ name, label, defaultValue = "" }: { name: string; label: string; defaultValue?: string }) { return <label className="grid gap-1 text-xs font-medium">{label}<input name={name} required={name !== "youtubeChannelId"} defaultValue={defaultValue} className="min-h-10 rounded-md border bg-[var(--surface)] px-3 text-sm" /></label>; }
