"use client";

import type { ColumnDef } from "@tanstack/react-table";
import { type FormEvent, useState } from "react";

import { ActionDialog } from "@/components/action-dialog";
import { DataTable } from "@/components/data-table";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Panel } from "@/components/ui/panel";
import type { DomainEntryList, Streamer } from "@/features/catalog/api";
import { useDomainEntries, useStreamers } from "@/features/catalog/api";
import { useAddDomainAlias, useArchiveDomainEntry, useCreateDomainEntry, useDeleteDomainAlias, useLinkDomainStreamer, useUnlinkDomainStreamer, useUpdateDomainEntry } from "@/features/configuration/api";

type Entry = DomainEntryList["items"][number];

export function KnowledgeConsole({ initialEntries, initialStreamers }: { initialEntries: DomainEntryList | null; initialStreamers: Streamer[] | null }) {
  const entries = useDomainEntries(initialEntries); const streamers = useStreamers(initialStreamers); const create = useCreateDomainEntry(); const update = useUpdateDomainEntry(); const archive = useArchiveDomainEntry(); const addAlias = useAddDomainAlias(); const deleteAlias = useDeleteDomainAlias(); const link = useLinkDomainStreamer(); const unlink = useUnlinkDomainStreamer(); const [selected, setSelected] = useState<Entry | null>(null);
  const current = selected && entries.data?.items.find((entry) => entry.entryId === selected.entryId) || selected;
  const columns: ColumnDef<Entry>[] = [
    { header: "ID", accessorKey: "entryId", cell: ({ getValue }) => <code translate="no">#{String(getValue())}</code> },
    { header: "Canonical", accessorKey: "canonicalName", cell: ({ row }) => <div><p className="font-medium">{row.original.canonicalName}</p><p className="text-xs text-[var(--muted)]">{row.original.displayName}</p></div> },
    { header: "유형", accessorKey: "typeKey", cell: ({ row }) => <span>{row.original.typeLabel} <code translate="no">({row.original.typeKey})</code></span> },
    { header: "정책", accessorKey: "promptPolicy", cell: ({ getValue }) => <code translate="no">{String(getValue())}</code> },
    { header: "별칭", accessorKey: "aliases", cell: ({ row }) => <span className="ops-number">{row.original.aliases.length}</span> },
    { header: "Streamer", accessorKey: "streamers", cell: ({ row }) => <span className="ops-number">{row.original.streamers.length}</span> },
    { header: "상태", accessorKey: "isActive", cell: ({ row }) => <StatusBadge value={row.original.isActive ? "active" : "archived"} /> },
    { header: "조작", id: "actions", cell: ({ row }) => <div className="flex gap-2"><Button size="sm" onClick={() => setSelected(row.original)}>편집</Button><ActionDialog.Provider heading={`지식 항목 #${row.original.entryId} archive`} description={`${row.original.canonicalName} 항목을 자동 프롬프트 대상에서 제외합니다.`} confirmLabel="Archive" confirmationValue={String(row.original.entryId)} reasonRequired tone="danger" onConfirm={(reason) => archive.mutateAsync({ id: row.original.entryId, reason }).then(() => undefined)}><ActionDialog.Trigger><Button size="sm" variant="destructive">Archive</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ReasonField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider></div> },
  ];
  function saveEntry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { canonicalName: String(form.get("canonicalName")), displayName: String(form.get("displayName")) || null, typeKey: String(form.get("typeKey")), typeLabel: String(form.get("typeLabel")), detail: String(form.get("detail")) || null, promptPolicy: String(form.get("promptPolicy")) as "AUTO_ON_MATCH" | "ALWAYS_FOR_SCOPED_STREAMER" | "DISABLED" }; if (current) void update.mutateAsync({ id: current.entryId, body }).then(() => setSelected(null)); else void create.mutateAsync(body).then(() => event.currentTarget.reset()); }
  return <><PageHeader eyebrow="구성" heading="Domain knowledge" description="고유명사, 별칭, ASR 오인식과 streamer 범위를 운영 프롬프트에 안전하게 연결합니다." />
    <Panel.Root className="mb-4"><Panel.Header><Panel.HeadingGroup><Panel.Title>{current ? `항목 #${current.entryId} 편집` : "지식 항목 추가"}</Panel.Title><Panel.Description>공개 fallback이 아닌 DB 운영 지식</Panel.Description></Panel.HeadingGroup></Panel.Header><Panel.Body><form key={current?.entryId ?? "new"} onSubmit={saveEntry} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Field name="canonicalName" label="Canonical name" defaultValue={current?.canonicalName} /><Field name="displayName" label="표시 이름" defaultValue={current?.displayName ?? ""} /><Field name="typeKey" label="Type key" defaultValue={current?.typeKey ?? "term"} /><Field name="typeLabel" label="Type label" defaultValue={current?.typeLabel ?? "용어"} /><label className="grid gap-1 text-xs font-medium">Prompt policy<select name="promptPolicy" defaultValue={current?.promptPolicy ?? "AUTO_ON_MATCH"} className="min-h-10 rounded-md border bg-[var(--surface)] px-3 font-mono text-sm"><option>AUTO_ON_MATCH</option><option>ALWAYS_FOR_SCOPED_STREAMER</option><option>DISABLED</option></select></label><label className="grid gap-1 text-xs font-medium md:col-span-2">설명<input name="detail" defaultValue={current?.detail ?? ""} className="min-h-10 rounded-md border bg-[var(--surface)] px-3 text-sm" /></label><div className="flex items-end gap-2"><Button type="submit" variant="primary" disabled={create.isPending || update.isPending}>{current ? "변경 저장" : "추가"}</Button>{current && <Button type="button" onClick={() => setSelected(null)}>취소</Button>}</div></form>
      {current && <div className="mt-5 grid gap-4 border-t pt-4 xl:grid-cols-2"><section><h3 className="mb-2 text-sm font-semibold">별칭</h3><form className="mb-2 flex gap-2" onSubmit={(event) => { event.preventDefault(); const surfaceForm = String(new FormData(event.currentTarget).get("surfaceForm")); void addAlias.mutateAsync({ entryId: current.entryId, body: { surfaceForm, aliasKind: "ALIAS", applyScope: "SEARCH_AND_SUMMARY", certainty: "HIGH" } }).then(() => event.currentTarget.reset()); }}><input name="surfaceForm" required className="min-h-10 min-w-0 flex-1 rounded-md border bg-[var(--surface)] px-3 text-sm" placeholder="새 별칭" /><Button type="submit">추가</Button></form><div className="grid gap-2">{current.aliases.map((alias) => <div key={alias.aliasId} className="flex items-center justify-between gap-2 rounded border p-2 text-sm"><span>{alias.surfaceForm} <code className="text-xs" translate="no">{alias.aliasKind}</code></span><ActionDialog.Provider heading={`별칭 #${alias.aliasId} 삭제`} description={`${alias.surfaceForm} 별칭 관계를 제거합니다.`} confirmLabel="삭제" confirmationValue={String(alias.aliasId)} reasonRequired tone="danger" onConfirm={(reason) => deleteAlias.mutateAsync({ aliasId: alias.aliasId, reason }).then(() => undefined)}><ActionDialog.Trigger><Button size="sm" variant="destructive">삭제</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ReasonField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider></div>)}</div></section>
      <section><h3 className="mb-2 text-sm font-semibold">Streamer 범위</h3><form className="mb-2 flex gap-2" onSubmit={(event) => { event.preventDefault(); const streamerId = Number(new FormData(event.currentTarget).get("streamerId")); void link.mutateAsync({ entryId: current.entryId, body: { streamerId, relevance: 100 } }); }}><select name="streamerId" className="min-h-10 min-w-0 flex-1 rounded-md border bg-[var(--surface)] px-3 text-sm">{streamers.data?.map((streamer) => <option key={streamer.id} value={streamer.id}>{streamer.name}</option>)}</select><Button type="submit">연결</Button></form><div className="grid gap-2">{current.streamers.map((streamer) => <div key={streamer.streamerId} className="flex items-center justify-between gap-2 rounded border p-2 text-sm"><span>{streamer.streamerName} <code translate="no">#{streamer.streamerId}</code></span><ActionDialog.Provider heading={`Streamer #${streamer.streamerId} 연결 해제`} description={`${current.canonicalName} 지식 항목과의 범위 관계를 제거합니다.`} confirmLabel="연결 해제" confirmationValue={String(streamer.streamerId)} reasonRequired tone="danger" onConfirm={(reason) => unlink.mutateAsync({ entryId: current.entryId, streamerId: streamer.streamerId, reason }).then(() => undefined)}><ActionDialog.Trigger><Button size="sm" variant="destructive">해제</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ReasonField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider></div>)}</div></section></div>}
    </Panel.Body></Panel.Root>
    <DataTable.Provider rows={entries.data?.items ?? []} columns={columns} getRowId={(row) => String(row.entryId)} state={{ initialLoading: entries.isLoading, refreshing: entries.isFetching && !entries.isLoading, placeholder: entries.isPlaceholderData, error: entries.error?.message ?? null }} meta={{ label: "Domain knowledge 목록", emptyTitle: "등록된 지식이 없습니다.", emptyDescription: "첫 지식 항목을 추가하세요." }}><DataTable.Frame><DataTable.Toolbar><span className="text-sm text-[var(--muted)]">활성 항목 {entries.data?.items.length ?? 0}개</span></DataTable.Toolbar><DataTable.Content /></DataTable.Frame></DataTable.Provider>
  </>;
}

function Field({ name, label, defaultValue = "" }: { name: string; label: string; defaultValue?: string }) { return <label className="grid gap-1 text-xs font-medium">{label}<input name={name} required={name === "canonicalName" || name === "typeKey" || name === "typeLabel"} defaultValue={defaultValue} className="min-h-10 rounded-md border bg-[var(--surface)] px-3 text-sm" /></label>; }
