"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { type FormEvent } from "react";

import { ActionDialog } from "@/components/action-dialog";
import { JsonInspector } from "@/components/json-inspector";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Panel } from "@/components/ui/panel";
import type { PromptSummary } from "@/features/catalog/api";
import { usePrompts } from "@/features/catalog/api";
import type { PromptDetail, PromptKey } from "@/features/configuration/api";
import { useArchivePromptVersion, useCreatePromptVersion, usePromptDetail, usePublishPromptVersion, useUpdatePromptVersion } from "@/features/configuration/api";
import { formatDateTime } from "@/lib/format";

const KEYS: PromptKey[] = ["micro_event_extract", "timeline_compose", "timeline_episode_repair"];

export function PromptsConsole({ initialPrompts, initialDetail, initialKey }: { initialPrompts: PromptSummary[] | null; initialDetail: PromptDetail | null; initialKey: PromptKey }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const key = (params.get("key") as PromptKey | null) ?? initialKey;
  const prompts = usePrompts(initialPrompts); const detail = usePromptDetail(key, key === initialKey ? initialDetail : null); const create = useCreatePromptVersion(key); const update = useUpdatePromptVersion(key); const publish = usePublishPromptVersion(key); const archive = useArchivePromptVersion(key);
  function select(nextKey: PromptKey) { const next = new URLSearchParams(params); next.set("key", nextKey); router.replace(`${pathname}?${next.toString()}`, { scroll: false }); }
  function createVersion(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); void create.mutateAsync({ versionLabel: String(form.get("versionLabel")), sourceNote: String(form.get("sourceNote")) || null, body: String(form.get("body")) }).then(() => event.currentTarget.reset()); }
  return <><PageHeader eyebrow="구성" heading="Prompt lifecycle" description="운영 DB prompt version을 draft → published → archived 상태로 관리합니다. 임의 prompt 실행은 제공하지 않습니다." />
    <div className="grid gap-4 xl:grid-cols-[16rem_minmax(0,1fr)]"><Panel.Root><Panel.Header><Panel.Title>Prompt keys</Panel.Title></Panel.Header><Panel.Body className="grid gap-2">{KEYS.map((item) => { const summary = prompts.data?.find((prompt) => prompt.key === item); return <button key={item} type="button" onClick={() => select(item)} aria-current={item === key ? "page" : undefined} className="min-h-12 rounded-md border px-3 py-2 text-left hover:bg-[var(--surface-muted)] aria-[current=page]:border-[var(--accent)] aria-[current=page]:bg-[var(--accent-soft)]"><code className="text-sm" translate="no">{item}</code><p className="mt-1 text-xs text-[var(--muted)]">{summary?.versionCount ?? 0} versions · {summary?.active?.versionLabel ?? "fallback"}</p></button>; })}</Panel.Body></Panel.Root>
    <div className="grid gap-4"><Panel.Root><Panel.Header><Panel.HeadingGroup><Panel.Title>Active prompt</Panel.Title><Panel.Description><code translate="no">{key}</code></Panel.Description></Panel.HeadingGroup><StatusBadge value={detail.data?.active.source ?? "fallback"} /></Panel.Header><Panel.Body><p className="mb-2 text-xs text-[var(--muted)]"><code translate="no">{detail.data?.active.versionLabel ?? "—"}</code> · <code translate="no">{detail.data?.active.bodySha256 ?? "—"}</code></p><pre className="ops-scrollbar max-h-96 overflow-auto whitespace-pre-wrap rounded-md border bg-[var(--surface-muted)] p-4 text-xs leading-5">{detail.data?.active.body ?? "활성 prompt가 없습니다."}</pre></Panel.Body></Panel.Root>
    <Panel.Root><Panel.Header><Panel.Title>새 draft</Panel.Title><Panel.Description>운영 품질 prompt 본문은 DB에만 저장</Panel.Description></Panel.Header><Panel.Body><form onSubmit={createVersion} className="grid gap-3"><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-medium">Version label<input name="versionLabel" required className="min-h-10 rounded-md border bg-[var(--surface)] px-3 font-mono text-sm" placeholder="v2026-07-14" /></label><label className="grid gap-1 text-xs font-medium">Source note<input name="sourceNote" className="min-h-10 rounded-md border bg-[var(--surface)] px-3 text-sm" /></label></div><label className="grid gap-1 text-xs font-medium">Prompt body<textarea name="body" required rows={10} className="resize-y rounded-md border bg-[var(--surface)] p-3 font-mono text-xs leading-5" /></label><Button type="submit" variant="primary" className="w-fit" disabled={create.isPending}>Draft 생성</Button></form></Panel.Body></Panel.Root>
    <Panel.Root><Panel.Header><Panel.Title>Versions</Panel.Title><Panel.Description>게시와 archive는 확인 후 실행</Panel.Description></Panel.Header><Panel.Body className="grid gap-2">{detail.data?.versions.map((version) => <article key={version.id} className="grid gap-3 rounded-md border p-3 lg:grid-cols-[8rem_minmax(0,1fr)_auto]"><div><code className="font-semibold" translate="no">#{version.id}</code><p className="text-xs text-[var(--muted)]">{formatDateTime(version.updatedAt)}</p></div><div><p className="font-mono text-sm" translate="no">{version.versionLabel}</p><div className="mt-1 flex gap-2"><StatusBadge value={version.status} />{version.isActive && <StatusBadge value="active" />}</div><form className="mt-2 flex gap-2" onSubmit={(event) => { event.preventDefault(); const sourceNote = String(new FormData(event.currentTarget).get("sourceNote")); void update.mutateAsync({ id: version.id, body: { sourceNote } }); }}><input name="sourceNote" defaultValue={version.sourceNote ?? ""} aria-label={`Version #${version.id} source note`} className="min-h-9 min-w-0 flex-1 rounded-md border bg-[var(--surface)] px-3 text-xs" /><Button size="sm" type="submit" disabled={version.status !== "DRAFT"}>메모 저장</Button></form></div><div className="flex flex-wrap content-start gap-2"><ActionDialog.Provider heading={`Prompt version #${version.id} 게시`} description={`${key}/${version.versionLabel}을 활성 운영 prompt로 전환합니다.`} confirmLabel="Publish" confirmationValue={String(version.id)} onConfirm={() => publish.mutateAsync(version.id).then(() => undefined)}><ActionDialog.Trigger><Button size="sm" variant="primary" disabled={version.status !== "DRAFT"}>Publish</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider><ActionDialog.Provider heading={`Prompt version #${version.id} archive`} description="이 버전을 archived 상태로 전환합니다. ID와 사유가 필요합니다." confirmLabel="Archive" confirmationValue={String(version.id)} reasonRequired tone="danger" onConfirm={(reason) => archive.mutateAsync({ id: version.id, reason }).then(() => undefined)}><ActionDialog.Trigger><Button size="sm" variant="destructive" disabled={version.status === "ARCHIVED"}>Archive</Button></ActionDialog.Trigger><ActionDialog.Content><ActionDialog.ConfirmationField /><ActionDialog.ReasonField /><ActionDialog.ErrorMessage /><ActionDialog.Footer /></ActionDialog.Content></ActionDialog.Provider></div></article>)}</Panel.Body></Panel.Root>
    <Panel.Root><Panel.Header><Panel.Title>원본 응답</Panel.Title></Panel.Header><JsonInspector value={detail.data} /></Panel.Root></div></div>
  </>;
}
