"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { apiError } from "@/features/api-error";
import { queryKeys } from "@/features/query-keys";
import type { components } from "@/generated/codex-api";
import { browserApi, operatorReasonHeader } from "@/lib/api";

export type PromptDetail = components["schemas"]["PromptDetailResponse"];
type StreamerCreate = components["schemas"]["StreamerCreateRequest"];
type StreamerUpdate = components["schemas"]["StreamerUpdateRequest"];
type ChannelCreate = components["schemas"]["ChannelCreateRequest"];
type ChannelUpdate = components["schemas"]["ChannelUpdateRequest"];
type DomainCreate = components["schemas"]["DomainEntryCreateRequest"];
type DomainUpdate = components["schemas"]["DomainEntryUpdateRequest"];
type AliasCreate = components["schemas"]["DomainEntryAliasCreateRequest"];
type StreamerLinkCreate = components["schemas"]["DomainEntryStreamerLinkRequest"];
type PromptCreate = components["schemas"]["PromptVersionCreateRequest"];
type PromptUpdate = components["schemas"]["PromptVersionUpdateRequest"];
export type PromptKey = components["schemas"]["PromptBodyResponse"]["key"];

async function invalidate(queryClient: ReturnType<typeof useQueryClient>, keys: readonly string[][]) { await Promise.all(keys.map((queryKey) => queryClient.invalidateQueries({ queryKey }))); }

export function useCreateStreamer() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: StreamerCreate) => { const { data, error } = await browserApi.POST("/ops/streamers", { body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["streamers"], ["channels"]]) }); }
export function useUpdateStreamer() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, body }: { id: number; body: StreamerUpdate }) => { const { data, error } = await browserApi.PATCH("/ops/streamers/{streamer_id}", { params: { path: { streamer_id: id } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["streamers"], ["channels"]]) }); }
export function useDeleteStreamer() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, reason }: { id: number; reason: string }) => { const { data, error } = await browserApi.DELETE("/ops/streamers/{streamer_id}", { params: { path: { streamer_id: id }, header: { "X-Operator-Reason": operatorReasonHeader(reason) } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["streamers"], ["channels"], ["events"]]) }); }
export function useCreateChannel() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ streamerId, body }: { streamerId: number; body: ChannelCreate }) => { const { data, error } = await browserApi.POST("/ops/streamers/{streamer_id}/channels", { params: { path: { streamer_id: streamerId } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["channels"]]) }); }
export function useUpdateChannel() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, body }: { id: number; body: ChannelUpdate }) => { const { data, error } = await browserApi.PATCH("/ops/channels/{channel_id}", { params: { path: { channel_id: id } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["channels"]]) }); }
export function useDeleteChannel() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, reason }: { id: number; reason: string }) => { const { data, error } = await browserApi.DELETE("/ops/channels/{channel_id}", { params: { path: { channel_id: id }, header: { "X-Operator-Reason": operatorReasonHeader(reason) } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["channels"], ["events"]]) }); }

export function useCreateDomainEntry() { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: Omit<DomainCreate, "isActive" | "priority"> & Partial<Pick<DomainCreate, "isActive" | "priority">>) => { const { data, error } = await browserApi.POST("/ops/domain-entries", { body: { ...body, isActive: body.isActive ?? true, priority: body.priority ?? 100 } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"]]) }); }
export function useUpdateDomainEntry() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, body }: { id: number; body: DomainUpdate }) => { const { data, error } = await browserApi.PATCH("/ops/domain-entries/{entry_id}", { params: { path: { entry_id: id } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"]]) }); }
export function useArchiveDomainEntry() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, reason }: { id: number; reason: string }) => { const { data, error } = await browserApi.DELETE("/ops/domain-entries/{entry_id}", { params: { path: { entry_id: id }, header: { "X-Operator-Reason": operatorReasonHeader(reason) } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"], ["events"]]) }); }
export function useAddDomainAlias() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ entryId, body }: { entryId: number; body: AliasCreate }) => { const { data, error } = await browserApi.POST("/ops/domain-entries/{entry_id}/aliases", { params: { path: { entry_id: entryId } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"]]) }); }
export function useDeleteDomainAlias() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ aliasId, reason }: { aliasId: number; reason: string }) => { const { data, error } = await browserApi.DELETE("/ops/domain-entry-aliases/{alias_id}", { params: { path: { alias_id: aliasId }, header: { "X-Operator-Reason": operatorReasonHeader(reason) } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"], ["events"]]) }); }
export function useLinkDomainStreamer() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ entryId, body }: { entryId: number; body: Omit<StreamerLinkCreate, "relevance"> & { relevance?: string | number | null } }) => { const { data, error } = await browserApi.POST("/ops/domain-entries/{entry_id}/streamers", { params: { path: { entry_id: entryId } }, body: { ...body, relevance: body.relevance == null ? null : String(body.relevance) } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"]]) }); }
export function useUnlinkDomainStreamer() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ entryId, streamerId, reason }: { entryId: number; streamerId: number; reason: string }) => { const { data, error } = await browserApi.DELETE("/ops/domain-entries/{entry_id}/streamers/{streamer_id}", { params: { path: { entry_id: entryId, streamer_id: streamerId }, header: { "X-Operator-Reason": operatorReasonHeader(reason) } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["knowledge"], ["events"]]) }); }

export function usePromptDetail(key: PromptKey, initialData?: PromptDetail | null) { return useQuery({ queryKey: [...queryKeys.prompts, key], queryFn: async () => { const { data, error } = await browserApi.GET("/ops/prompts/{promptKey}", { params: { path: { promptKey: key } } }); if (!data) throw apiError(error); return data; }, initialData: initialData ?? undefined }); }
export function useCreatePromptVersion(key: PromptKey) { const qc = useQueryClient(); return useMutation({ mutationFn: async (body: PromptCreate) => { const { data, error } = await browserApi.POST("/ops/prompts/{promptKey}/versions", { params: { path: { promptKey: key } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["prompts"]]) }); }
export function useUpdatePromptVersion(key: PromptKey) { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, body }: { id: number; body: PromptUpdate }) => { const { data, error } = await browserApi.PATCH("/ops/prompts/{promptKey}/versions/{versionId}", { params: { path: { promptKey: key, versionId: id } }, body }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["prompts"]]) }); }
export function usePublishPromptVersion(key: PromptKey) { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: number) => { const { data, error } = await browserApi.POST("/ops/prompts/{promptKey}/versions/{versionId}/publish", { params: { path: { promptKey: key, versionId: id } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["prompts"]]) }); }
export function useArchivePromptVersion(key: PromptKey) { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, reason }: { id: number; reason: string }) => { const { data, error } = await browserApi.POST("/ops/prompts/{promptKey}/versions/{versionId}/archive", { params: { path: { promptKey: key, versionId: id }, header: { "X-Operator-Reason": operatorReasonHeader(reason) } } }); if (!data) throw apiError(error); return data; }, onSuccess: () => invalidate(qc, [["prompts"], ["events"]]) }); }
